import { Button, Typography } from 'antd'
import Head from 'next/head'
import styles from '@/styles/pages/index.module.scss'
import { useState } from 'react'

const { Text, Title } = Typography

export default function Home() {
  const [clickCount, setClickCount] = useState(0)

  return (
    <>
      <Head>
        <title>BTB Ant Design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.mainContent}>
        <Title>BTB Ant Design</Title>
        <Text>
          This repo is made as a reference of how to implement{' '}
          <Text strong>Ant Design</Text> to a project.
        </Text>
        <br />
        <Button type="primary" onClick={() => setClickCount(clickCount + 1)}>
          {clickCount
            ? `Clicked ${clickCount} time${clickCount > 1 ? 's' : ''}`
            : 'Click me!'}
        </Button>
      </div>
    </>
  )
}
